version: '3.8'
services:
  order1:
    image: ms-order
    hostname: order1
    container_name: order1
    ports:
      - "10000:80"
  order2:
    image: ms-order
    hostname: order2
    container_name: order2
    ports:
      - "10001:80"
  order3:
    image: ms-order
    hostname: order3
    container_name: order3
    ports:
      - "10002:80"
networks:
  network1:
    name: msnetwork
    external: true