version: '3.8'
services:
  cofigserver:
    image: node-configuration
    hostname: cofigserver
    container_name: cofigserver
    ports:
      - "8888:80"
  discovery:
    image: node-discovery
    hostname: discovery
    container_name: discovery
    ports:
      - "5555:80"
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    container_name: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
networks:
  network1:
    name: msnetwork
    external: true